name: grocdrop
description: "GrocDrop Flutter App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  http: ^1.2.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1


  # Firebase (optional â€“ keep if still used)
  firebase_core: ^3.7.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1

  # Utils / Payments
  razorpay_flutter: ^1.3.7
  pdf: ^3.10.4
  path_provider: ^2.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/products/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
